openapi: 3.0.1
info:
  title: 008-httpbin-headers-jenkins
  description: 008 Demo OpenAPI Specification for CICD
  version: '1.0'
  contact:
    email: david.macdonald@konhq.com

servers:
  - url: https://httpbin.org

tags:
  - name: TagB
    description: Operations for testing headers

paths:

  /headers:
    get:
      summary: Returns the request headers.
      description: Header service
      operationId: getHeaders
      tags:
      - TagB
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  headers:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - headers
